version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      # - echo Nothing to do in the pre_build phase...
      - pip install -r requirements.txt
  build:
    commands:
      - printenv
      - echo Build started on $AWS_REGION
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/artifact.zip